module.exports = {
  defaultSeverity: 'error',
  // https://github.com/palantir/tslint/blob/a3d8d6fd5a52537e7d61f2759b68980c649a7685/src/configs/all.ts
  rules: {
    'adjacent-overload-signatures': true,
    'align': {
      options: [
        'parameters',
        'arguments',
        'statements',
      ],
    },
    'array-type': {
      options: ['array'],
    },
    'arrow-parens': {
      options: ['ban-single-arg-parens'],
    },
    'arrow-return-shorthand': true,
    'await-promise': false,
    'ban': false,
    'ban-types': {
      options: [
        ['Object', 'Avoid using the `Object` type. Did you mean `object`?'],
        ['Boolean', 'Avoid using the `Boolean` type. Did you mean `boolean`?'],
        ['Number', 'Avoid using the `Number` type. Did you mean `number`?'],
        ['String', 'Avoid using the `String` type. Did you mean `string`?'],
        ['Symbol', 'Avoid using the `Symbol` type. Did you mean `symbol`?'],
      ],
    },
    'callable-types': true,
    'class-name': true,
    'comment-format': {
      options: [
        'check-space',
        'check-uppercase',
      ],
    },
    'completed-docs': false,
    'curly': true,
    'cyclomatic-complexity': false,
    'eofline': true,
    'file-header': false,
    'forin': false,
    'import-blacklist': false,
    'import-spacing': true,
    'indent':  {
      options: ['spaces'],
    },
    'interface-name': {
      options: ['never-prefix'],
    },
    'interface-over-type-literal': true,
    'jsdoc-format': true,
    'label-position': true,
    'linebreak-style': {
      options: ['LF'],
    },
    'match-default-export-name': false,
    'max-classes-per-file': false,
    'max-file-line-count': false,
    'max-line-length': {
      options: [120],
    },
    'member-access': {
      options: ['no-public'],
    },
    'member-ordering': {
      options: {
        order: [
          'public-instance-field',
          'protected-instance-field',
          'private-instance-field',
          'public-constructor',
          'protected-constructor',
          'private-constructor',
          'public-instance-method',
          'protected-instance-method',
          'private-instance-method',
          'public-static-field',
          'public-static-method',
          'protected-static-field',
          'protected-static-method',
          'private-static-field',
          'private-static-method'
        ],
      },
    },
    'newline-before-return': false,
    'new-parens': true,
    'no-angle-bracket-type-assertion': true,
    'no-any': false,
    'no-arg': true,
    'no-bitwise': true,
    'no-boolean-literal-compare': true,
    'no-conditional-assignment': true,
    'no-consecutive-blank-lines': true,
    'no-console': true,
    'no-construct': true,
    'no-debugger': true,
    'no-default-export': false,
    'no-duplicate-super': true,
    'no-duplicate-variable': true,
    'no-empty': false,
    'no-empty-interface': true,
    'no-eval': false,
    'no-floating-promises': true,
    'no-for-in-array': true,
    'no-import-side-effect': false,
    'no-inferrable-types': false,
    'no-inferred-empty-object-type': true,
    'no-internal-module': true,
    "no-invalid-template-strings": true,
    'no-invalid-this': false,
    'no-magic-numbers': false,
    'no-mergeable-namespace': true,
    'no-misused-new': true,
    'no-namespace': false,
    'no-non-null-assertion': false,
    'no-null-keyword': true,
    'no-parameter-properties': false,
    'no-reference': true,
    'no-reference-import': true,
    'no-require-imports': true,
    'no-shadowed-variable': false,
    "no-sparse-arrays": true,
    'no-string-literal': true,
    'no-string-throw': true,
    'no-switch-case-fall-through': true,
    'no-trailing-whitespace': true,
    'no-unbound-method': true,
    'no-unnecessary-callback-wrapper': false,
    'no-unnecessary-initializer': true,
    'no-unnecessary-qualifier': true,
    'no-unsafe-any': false,
    'no-unsafe-finally': true,
    'no-unused-expression': true,
    'no-unused-variable': false,
    'no-use-before-declare': false,
    'no-var-keyword': true,
    'no-var-requires': true,
    // TODO: https://github.com/palantir/tslint/issues/2473
    'no-void-expression': false,
    'object-literal-key-quotes': {
      options: ['as-needed'],
    },
    'object-literal-shorthand': true,
    'object-literal-sort-keys': false,
    'one-line': {
      options: [
        'check-catch',
        'check-else',
        'check-finally',
        'check-open-brace',
        'check-whitespace',
      ],
    },
    'one-variable-per-declaration': {
      options: ['ignore-for-loop'],
    },
    'only-arrow-functions': {
      options: [
        'allow-declarations',
        'allow-named-functions',
      ],
    },
    'ordered-imports': {
      options: {
        'import-sources-order': 'case-insensitive',
        'named-imports-order': 'lowercase-last',
      },
    },
    'prefer-const': false,
    'prefer-for-of': true,
    'prefer-function-over-method': false,
    'prefer-method-signature': true,
    'prefer-template': true,
    // TODO:
    'promise-function-async': false,
    'quotemark': {
      options: ['single'],
    },
    'radix': false,
    'restrict-plus-operands': false,
    'return-undefined': true,
    'semicolon': {
      options: ['always'],
    },
    'space-before-function-paren': {
      options: {
        anonymous: 'always',
        asyncArrow: 'always',
        constructor: 'never',
        method: 'never',
        named: 'never',
      },
    },
    'strict-boolean-expressions': false,
    // TODO: https://github.com/palantir/tslint/issues/2472
    'strict-type-predicates': false,
    'switch-default': false,
    'trailing-comma': {
      options: {
        multiline: 'always',
        singleline: 'never',
      },
    },
    'triple-equals': {
      options: ['allow-null-check'],
    },
    'typedef': false,
    'typedef-whitespace': {
      options: [
        {
          'call-signature': 'nospace',
          'index-signature': 'nospace',
          'parameter': 'nospace',
          'property-declaration': 'nospace',
          'variable-declaration': 'nospace',
        },
        {
          'call-signature': 'onespace',
          'index-signature': 'onespace',
          'parameter': 'onespace',
          'property-declaration': 'onespace',
          'variable-declaration': 'onespace',
        },
      ],
    },
    'typeof-compare': true,
    'unified-signatures': true,
    'use-isnan': true,
    'variable-name': {
      options: [
        'ban-keywords',
        'check-format',
        'allow-leading-underscore',
        'allow-pascal-case',
      ],
    },
    'whitespace': {
      options: [
        'check-branch',
        'check-decl',
        'check-operator',
        'check-module',
        'check-separator',
        'check-type',
        'check-typecast',
        'check-preblock',
      ],
    },
  },
};
